apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pod-health-check
  namespace: default
spec:
  metrics:
    - name: unavailable-pods
      count: 3  # Run this check 3 times before deciding success or failure
      interval: 30s  # Run every 30 seconds
      successCondition: "result[0] == 0"  # Pass if no pods are failing
      failureCondition: "result[0] > 0"   # Fail if there are failing pods
      provider:
        kubernetes:
          query: |
            jsonpath='{.items[*].status.phase}'
          resource:
            apiVersion: v1
            kind: Pod
            namespace: default
            selector:
              matchLabels:
                app: nginx
