apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pod-health-check
  namespace: default
spec:
  startingStep: 1  # ✅ Ensures analysis runs even on initial deploy
  metrics:
    - name: unavailable-pods
      count: 3
      interval: 30s
      successCondition: "result[0] == 0"
      failureCondition: "result[0] > 0"
      provider:
        kubernetes:
          query: |
            jsonpath='{.items[*].status.phase}'
          resource:
            apiVersion: v1
            kind: Pod
            namespace: default
            selector:
              matchLabels:
                app: nginx
