apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
  namespace: default
spec:
  rollbackWindow:
    revisions: 3
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 1m }
        - analysis:
            templates:
              - templateName: pod-health-check
            rollbackOnFailure: true  # ✅ Enables rollback on failed analysis
        - setWeight: 100
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: httpd:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 800
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 800
            initialDelaySeconds: 10
            periodSeconds: 10
  progressDeadlineSeconds: 600
